# Generated by Django 4.0.1 on 2022-02-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='advice',
            field=models.CharField(default='adv', max_length=200),
        ),
    ]
